### ISSUE TITLE
C++ Alternative Build System

### ISSUE THREAD

**Issue by geogunow** [mit-crpg/OpenMOC#159]
I'm not sure if this belongs in the issues section, but it might really help to have an alternative build system that just uses C++ (instead of SWIG) with compiled inputs for common cases (such as C5G7). It looks like this could be simple as the C++ source files wouldn't need to be changed at all.

Adding this option would allow form much easier performance profiling and debugging as well. Everyone in CESAR would rejoice. Let me know what you guys think and if there are any issues you see that might arise. I would envision this as a separate "profiling" directory containing a makefile and then maybe two or three hard-baked C++ input files like C5G7.cpp or LRA.cpp.

**Comment by PrezNattyGibbs** [comment]
Certainly seems like a reasonable use of the issue tracker!

It'd also help with running the code through valgrind and various other tools that get cranky with Python.  I support this (but don't volunteer to do it!).

**Comment by geogunow** [comment]
I can do this, but I would first like to hear from everyone if they foresee any issues. Of course I won't put in plotting, just the solver since C++ plotting can be messy. But there might be other python interfaces that might be difficult. In particular, how would I pull the material data? Right now it seems that is done entirely in python with an included python file in the openmoc directory (materialize.py). How could this be changed for C++?

**Comment by PrezNattyGibbs** [comment]
The `materialize` module is in Python, not C++, yes.  But all the material setting routines are also in C++, so it's only an issue of pulling data out of HDF5.  The c5g7 data really isn't that much, so you could even just hard code a data block for your purposes if you didn't want to deal with HDF5.

Lattices could get a little funny without the Python interface (and numpy arrays).  But I don't think it'd be too painful to do it with C++ arrays.

I don't think there are any other places where you'd have to do more than declaring all your variable names and then directly translating the input files line by line.

**Comment by wbinventor** [comment]
It probably comes with no surprise that I think a pure C++/CUDA build with compiled inputs is a return to the dark ages from a usability standpoint. Nonetheless, I fully understand that Python/C++ integration is a very ineffective way to build the code for performance profiling and analysis. Hence, I think that a pure C++/CUDA build option is a fine goal to have.

I agree with @PrezNattyGibbs that this *shouldn't* be very difficult to implement. At its simplest, you can write a Makefile (or use CMake to generate one for you - you might use OpenMC's build system as a reference for this) to compile and link the source files with some of the same command line arguments we use for the Distutils build system (I think ``config.py`` is pretty self-explanatory here). A few of the command line arguments will not be relevant, however, since they are needed to build OpenMOC as a shared library rather than as an executable (*e.g.*, ``-shared``, ``-fPIC``).

As you've noted, you'll also need to compile the inputs unless you want to write your own ASCII or XML input parser (which you probably don't want to do...one advantage of SWIG is that it effectively allows Python to act as an incredibly powerful and flexible input parser). I think you could easily copy the code from one of our Python input scripts into a "main.cpp" file and with few conversions from Python to C++ syntax you'll have yourself a compilable C++ input file.

Although the ``materialize`` module is in Python and uses the ``h5py`` module to read/write HDF5 files it wouldn't be hard to hard-code materials data as numerical arrays in a C++ source file. If you just wanted to do this the quick and dirty way, I would suggest looking at the ["sample-input/c5g7-materials.py"](https://github.com/mit-crpg/ClosedMOC/blob/develop/sample-input/c5g7-materials-hdf5.py) file which includes all of the C5G7 multi-group cross-sections for use on machines without HDF5/``h5py``. You can simply copy and paste this into a C++ file and make some minor changes to properly allocate the array memory.

As an aside, if it is indeed as easy as I think it will be to copy a Python input file into C++ syntax, it would be kind of cool to create a utility Python script to automate this process. The user would give the script the path to a working OpenMOC Python input script and it would parse this and convert it into a compilable C++ source file. Similarly, you could easily write a Python script to take in an HDF5 file of materials data, and write it to a new ASCII C++ compilable source file with "hard-coded" numerical arrays of the cross-section data. This would be useful so you have more flexibility to explore the performance when using more materials/energy groups than in the C5G7 benchmark.

**Comment by wbinventor** [comment]
After a little more thought, I think I know a much simpler route that you might take to go about this - I'm not sure why I didn't think of this sooner, but better late than never. 

Instead of copy-pasting a Python input script, you should make use of OpenMOC's track files. If the C++ build system is truly only for profiling purposes, then you can still use the Python bindings to build a geometry and perform ray tracing. The ``TrackGenerator`` will dump all of the tracks to a binary file in the "tracks" directory which you can use in a pure C++ executable.

In particular, your executable might take in the path/filename to a tracks binary file as a command line argument, *i.e.*,

```bash
openmoc /path/to/my/trackfile.tracks
```

By doing this you would avoid the hassle of having to setup and build a C++ file with all of the geometry. However, this approach would still require you to come up with a way to import materials data. But I think that it would likely be simpler to come up with a scheme to parse materials data from an ASCII file - given some layout specifications for such a file - than to convert Python geometries into C++ code. A Python script - or even better, and additional routine to the ``openmoc.materialize`` module - could be written to convert an HDF5 materials file into a compatible ASCII text file.

Per our discussion on #157 - I understand that using track files would preclude one from profiling the ray tracing portion of the OpenMOC codebase.
