### ISSUE TITLE
Adding Nvidia Optix Ray Tracing

### ISSUE THREAD

**Issue by geogunow** [mit-crpg/OpenMOC#166]
Recently, Tony Scudiero from Nvidia reached out to @jtramm and I regarding their ray tracing software called Optix. After a couple of meetings with @samuelshaner, @jtramm, and I, it seems like their ray tracing capability has great potential for OpenMOC.

Nvidia has quite a bit of experience with ray tracing and has released Optix which has great flexibility, allowing incorporation into a variety of applications. Indeed, OpenMOC could fit its mold. The results it claims for common ray tracing problems are incredible. I will be working part-time on incorporating this into OpenMOC in a separate branch with whoever would like to help out. If results are good enough, we could even consider having our main ray tracing powered by Optix.

**Comment by wbinventor** [comment]
I really like this idea as well @geogunow! This something I had considered
with great potential since first getting into GPUs a few years back.

I have two thoughts or concerns about this that come to mind at the moment.
First, we would want to preserve the flexibility offered by CSG if we were
to adopt OptiX's own primitives. In particular, I'd be curious to know if
they offer something similar to a lattice for repeated structures (or if
you have to replicate primitives, ie pin cells, all over the place).
Second, we certainly would want to keep a ray tracer for execution on CPUs.
Perhaps OptiX can be compiled into x86 code, I'm not sure.

You might want to chat with @mjlomg about this since he spent quite a bit
of time this past fall and spring looking at OptiX Ray tracing for OpenMC.
I don't believe be was very impressed :-( Although it can be dangerous to
drink NVIDIA's Kool-Aid sometimes, my guess is there is a good way to go
about this and if Tony Scudiero is willing to help, that would be great.

**Comment by geogunow** [comment]
Yeah, I agree. I am just starting to look into this so I'll know more once
I start getting my hands dirty. We did bring up to point about CSG and Tony
said that CSG is actually what they prefer to deal with. I could get into
the details but it would probably go into more detail than you bargained
for, and I would probably get some details wrong at this point.

I'm a bit more optimistic about our application over OpenMC since MOC is
more similar to the ray tracing NVIDIA performs for graphics.

**Comment by mjlong** [comment]
I heard you already have equations for irregular geometry in MOC like segments of rings. If those are equations for intersection of ray and a region not boundary of the region, my worry isn't a big deal.

**Comment by wbinventor** [comment]
@mjlong all of the ray tracing is done for intersection of a ray and boundaries of a region. The way this is done for segments of rings is through the convolution of multiple intersection calculations with each bounding surface.

What exactly were the issues you ran into with your exploratory work with OptiX?

**Comment by wbinventor** [comment]
@geogunow you might be interested in [this](https://github.com/mit-crpg/openmc/pull/408) new code change to the OpenMC code. This change could be similarly applicable to OpenMOC to improve ray tracing parallel performance.

In particular, this change would make ``LocalCoords`` objects statically rather than dynamically allocated for ray tracing. Presently, as each ``segment`` is traced across the geometry, the code will dynamically allocate memory for a new ``LocalCoords`` objects at each level (``Universe``, ``Cell``, ``Lattice``) of the CSG tree. After an intersection point has been found and a new ``segment`` has been created, one or more of the ``LocalCoords`` objects at each of those levels will be deallocated from memory. This is repeated over and over for each of the ``segments`` in a problem. By statically allocating a linked list of 10-15 ``LocalCoords`` ahead of time, the code may improve its parallel performance by eliminating "redundant" memory allocation at the sake of runtime flexibility to process complex geometries. 

I actually implemented static allocation for ``LocalCoords`` in 2012, but unfortunately saw no performance benefit. However, it is possible that many of the structural changes made to the ray tracing code since then have removed the bottlenecks that may have "hidden" the need to use static allocation. On the flip side, from what I have seen of the ray tracing logic in each code, I do no think that static allocation would improve OpenMOC's performance as much as it does for OpenMC since we use more memoiz'ation of ``LocalCoords`` within each nested ``Universe`` level. Even still, it might be worth considering this as an optimization experiment along with OptiX as one possible pathway to improve ray tracing performance.

**Comment by mjlong** [comment]
@wbinventor you were aware of the issue I ran into. The intersection point solved by ray tracing function could numerically be on either side of the surface. But this happens to most ray tracing program I believe. 

Optix is good at ray tracing for isolated or nested geometries. It might lose some benefit when performing ray tracing in the adjacent geometry objects of MOC. Now we have the equations for each segment. But when Optix traces one ray, (in the worst case) all segments will be tested. If there are 4 azimuthal regions, the equation of the inner and outer cycle of the ring would be solved for 4 times.  That number would be 8 for the circle shared by two rings.

**Comment by geogunow** [comment]
Due to the struggles of @jtramm I'm going to close this issue
