### ISSUE TITLE
Seg fault in ParallelHashMap.h

### ISSUE THREAD

**Issue by samuelshaner** [mit-crpg/OpenMOC#265]
I've been running into a seg fault when trying to run some LRA cases that appears to be in `ParallelHashMap.h` on line 190. I ran the profile version of OpenMOC with debugging turned on with an LRA-like input file included below. The bug occurs during segmentation and can be reproduced by compiling the input file below (with debugging turned on) and running with gdb. The second file below includes the gdb output showing the error.

@geogunow - any ideas on why there would be a seg fault on line 190 of `ParallelHashMap.h`?

[lra-cmfd.cpp.txt](https://github.com/mit-crpg/OpenMOC/files/131291/lra-cmfd.cpp.txt)
[lra-cmfd-output.txt](https://github.com/mit-crpg/OpenMOC/files/131298/lra-cmfd-output.txt)

**Comment by geogunow** [comment]
Yeah, It's probably during a resize. I'll take a look at it.

**Comment by samuelshaner** [comment]
Also, is there any reason for the `#ifdef OPENMP` preprocessor directives? Elsewhere in OpenMOC we just assume that OpenMP is present.

**Comment by geogunow** [comment]
I don't think this is the problem, but I found that there will be a seg fault if the user tries to set more threads than the number of physical cores

**Comment by geogunow** [comment]
I have come up with a solution that I will create a PR for tomorrow once I polish it for merging. The problem is that having an ``at`` function in ``ParallelHashMap`` that can assign values is fundamentally flawed. That's probably also why you don't find that kind of function in any mainstream parallel hash map implementation. Looks like I tried to get a little too cute when I first created it :)

**Comment by wbinventor** [comment]
Closed with #270.
