### ISSUE TITLE
SPH examples bugs

### ISSUE THREAD

**Issue by GiudGiud** [mit-crpg/OpenMOC#333]
Opening an issue here to document:
-various bugs in sph examples
-why it doesnt get exact preservation, when I ll have figured it out

**Comment by GiudGiud** [comment]
In the pin cell example, openmoc.materialize.compute_sph_factors is called with the wrong arguments

**Comment by wbinventor** [comment]
I can't speak for the bugs, but my guess is some are due to changes to the openmc.mgxs module in the last few months. These are way to "fix", simply by re-generating the XML files, running OpenMC, pickling the MGXS library, and finally running SPH (all in that order).

As for the exact preservation, note that neither OpenMC nor OpenMOC are converged here, so you wouldn't expect exact conservation. Look at my thesis for an idea of the parameters I used to converge to very nearly exact preservation (1 pcm). Those parameters require a lot of CPU-hours, and hence aren't appropriate for an example.

**Comment by GiudGiud** [comment]
Hey Will! Glad to hear from you. I heard there's a heat wave in your area rn!
True. I definitely had a lot of trouble with that earlier.

You're right, both calculations are unconverged. But it's to the point that SPH barely makes a difference. And by increasing the number of angles and decreasing track spacing, I actually get worse results with SPH. I would include the option to add rings in the fuel and coolant in the example, just to make things more clear. 

Another bug:
- SEG_FAULT at line 598
if throttle_output:
            openmoc.set_log_level(log_level)
For some reason I can't even print log_level, I get a utf-8 error from Python. 
Not a big deal, one can replace log_level by 'NORMAL'
