### ISSUE TITLE
CUDA outdated

### ISSUE THREAD

**Issue by gridley** [mit-crpg/OpenMOC#392]
Hi,

Seems like CUDA is pretty outdated here; config.py defaults to arch=compute_20 but most cards nowadays are at least arch=compute50 (GTX 900 series and up). I'd really like to check out the speedup attainable on a GTX 1070 with CUDA 9, but it seems that compute_20 architecture has been deprecated as of CUDA 9. This would ordinarily be an easy fix, just changing nvcc flags, but requires some extra work.

It seems there is a #include <sm_20_atomic_functions.h> in GPUSolver.h. I'm not sure what's being used from that, but it will likely have to be updated to work with newer CUDA. Also, GPUSolver defines its own atomicAdd kernel. Newer CUDA comes with atomicAdd, which causes a compiler error if you're above a certain version. A simple macro could give compatibility on both new and older archs.

Also, tuning on newer architectures is its own topic, which could possibly be tackled as well.

**Comment by GiudGiud** [comment]
Hi Gavin,

The GPU solver was developed by @wbinventor for his master's thesis ([https://dspace.mit.edu/handle/1721.1/87494]) 5 years ago. GPUs have changed a lot since then, and it looks like they don't provide retro-compatibility. Unfortunately we haven't been updating it.

We would absolutely welcome a PR if you were to update the GPU solver. Whether MOC solvers belong on CPUs or GPUs remains a hot topic.

**Comment by gridley** [comment]
Thanks for the info, I will very possibly take this on! :D

Gavin Ridley

**Comment by gridley** [comment]
done in #440
